"""Add combined score fields

Revision ID: 6e24d3eb886f
Revises: baa86a3211e5
Create Date: 2026-06-24 02:41:48.761443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e24d3eb886f'
down_revision: Union[str, Sequence[str], None] = 'baa86a3211e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_results', sa.Column('linkedin_manual_score', sa.Integer(), nullable=True))
    op.add_column('screening_results', sa.Column('linkedin_notes', sa.Text(), nullable=True))
    op.add_column('screening_results', sa.Column('linkedin_status', sa.String(length=50), server_default='unchecked', nullable=False))
    op.add_column('screening_results', sa.Column('github_consistency_score', sa.Integer(), nullable=True))
    op.add_column('screening_results', sa.Column('github_reasoning', sa.Text(), nullable=True))
    op.add_column('screening_results', sa.Column('github_status', sa.String(length=50), server_default='not_checked', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'github_status')
    op.drop_column('screening_results', 'github_reasoning')
    op.drop_column('screening_results', 'github_consistency_score')
    op.drop_column('screening_results', 'linkedin_status')
    op.drop_column('screening_results', 'linkedin_notes')
    op.drop_column('screening_results', 'linkedin_manual_score')
    # ### end Alembic commands ###
