"""Add jobs table

Revision ID: 6f18ba9bdc5e
Revises: a5aa18797579
Create Date: 2026-06-22 06:45:19.102772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f18ba9bdc5e'
down_revision: Union[str, Sequence[str], None] = 'a5aa18797579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_details', sa.Text(), nullable=True),
    sa.Column('raw_jd', sa.Text(), nullable=False),
    sa.Column('polished_jd', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'JD_GENERATED', 'APPROVED', 'REJECTED', 'PUBLISHED', name='job_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
