"""add social_assets table

Revision ID: 9608c0d00cc7
Revises: 6f18ba9bdc5e
Create Date: 2026-06-22 09:19:05.638533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9608c0d00cc7'
down_revision: Union[str, Sequence[str], None] = '6f18ba9bdc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'TWITTER', 'FACEBOOK', 'INSTAGRAM', name='social_platform'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('suggested_communities', sa.JSON(), nullable=False),
    sa.Column('visual_title', sa.String(length=255), nullable=False),
    sa.Column('visual_company', sa.String(length=255), nullable=False),
    sa.Column('visual_location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'platform', name='uq_social_asset_job_platform')
    )
    op.create_index(op.f('ix_social_assets_id'), 'social_assets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_assets_id'), table_name='social_assets')
    op.drop_table('social_assets')
    # ### end Alembic commands ###
