from abc import ABC, abstractmethod
from typing import Optional

class BaseLLMProvider(ABC):
    """Abstract Base Class specifying standard interface methods for LLM interactions."""

    @abstractmethod
    async def generate_text(
        self, prompt: str, system_instruction: Optional[str] = None
    ) -> str:
        """Generates a text completion based on the given prompt and system instructions.

        Args:
            prompt: The untrusted user content combined with task prompts.
            system_instruction: The core system identity and formatting constraints.

        Returns:
            The raw text generated by the model.
        """
        pass
